#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with dsh runtime deps.
# 依赖来源优先级：AGENT_RUNTIME（桌面端 agent/node_modules，rc7）→ DSH_CHECKOUT（旧 checkout，回退）。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# AGENT_RUNTIME 探测：环境变量 → 常见路径（APPDATA 下 DSH Desktop/agent）
AGENT_ROOT="${AGENT_RUNTIME:-}"
if [ -z "$AGENT_ROOT" ]; then
  for base in "${APPDATA:-}/DSH Desktop/agent" "${USERPROFILE:-}/AppData/Roaming/DSH Desktop/agent" "${LOCALAPPDATA:-}/DSH Desktop/agent"; do
    if [ -n "$base" ] && [ -d "$base/node_modules/@deepseek-ai" ]; then AGENT_ROOT="$base"; break; fi
  done
fi
if [ -z "$AGENT_ROOT" ]; then
  for base in /mnt/c/Users/*/AppData/Roaming/DSH\ Desktop/agent /mnt/d/Users/*/AppData/Roaming/DSH\ Desktop/agent; do
    if [ -d "$base/node_modules/@deepseek-ai" ]; then AGENT_ROOT="$base"; break; fi
  done
fi
# DSH_CHECKOUT 回退（旧逻辑）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi

if [ -n "$AGENT_ROOT" ] && [ -d "$AGENT_ROOT/node_modules/@deepseek-ai" ]; then
  SRC="$AGENT_ROOT/node_modules"
  echo "=== 使用 agent runtime 依赖: $SRC ==="
elif [ -n "$CHECKOUT" ] && [ -d "$CHECKOUT/packages" ]; then
  SRC="$CHECKOUT"
  echo "=== 使用 checkout 依赖（回退）: $CHECKOUT ==="
else
  echo "build: cannot locate runtime deps (set AGENT_RUNTIME or DSH_CHECKOUT)" >&2
  exit 1
fi

# tsc：优先本地 devDep，其次 checkout
TSC="node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  TSC="$CHECKOUT/node_modules/.bin/tsc"
fi
if [ -z "${TSC:-}" ] || { [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; }; then
  echo "build: tsc not found" >&2
  exit 1
fi

link_pkg() {
  local link="$1"
  local target="$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  if [ -e "$link" ]; then
    echo "    (keep existing $link)" >&2
    return 0
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "$link" "$target"
}

echo "=== Linking build dependencies ==="
mkdir -p node_modules/@deepseek-ai
link_pkg node_modules/@deepseek-ai/dsh-tools "$SRC/@deepseek-ai/dsh-tools"
link_pkg node_modules/@deepseek-ai/schemastery "$SRC/@deepseek-ai/schemastery"
link_pkg node_modules/@deepseek-ai/dsh-skill "$SRC/@deepseek-ai/dsh-skill"
link_pkg node_modules/@deepseek-ai/dsh-llm "$SRC/@deepseek-ai/dsh-llm"
# yaml 用于解析 SKILL.md frontmatter 的 `>` 折叠语法
if [ -d "$SRC/yaml" ]; then
  link_pkg node_modules/yaml "$SRC/yaml"
elif [ -d "$SRC/../yaml" ]; then
  link_pkg node_modules/yaml "$SRC/../yaml"
fi
if [ -d "$SRC/@types/node" ]; then
  link_pkg node_modules/@types/node "$SRC/@types/node"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="